### ISSUE TITLE
User Story 2: Entrylist

### ISSUE THREAD

**Issue by IrisHerholz** [IrisHerholz/capstone-project#2]
## Value Proposition

**As a** User
**I want to** be able to see all entries of one journey
**so that** I have an overview about all past entries.

## Description

![Bildschirmfoto 2023-01-27 um 11 51 19](https://user-images.githubusercontent.com/118169582/215068958-aa49b6ef-24a7-419d-a6f1-6f1cb8366c2f.png)

## Acceptance Criteria

- A heading is displayed
- The date is displayed.
- A list of journal entries is displayed 
- Each Entry title is displayed for each entry
- A back button is displayed

## Tasks

- create a folder in components with folder the name "JournalEntryList" and an index.js
- create a title and fix it on top of the list entry page
- create a project component to render each project data 
- in this folder create a data. file with static data for your list 
- import your file and map over the data 
- add a page for the displayed entries from the component "JournalEntryList"
- add back button to landing page
- add a button of the landing page to go to the entry list page

## Complexity

S

**Comment by NikRoe** [comment]
Hi Iris,

this looks like a very promising start!

I would change the app's behaviour slightly (though this is just a suggestion):
While a user adds a new entry, the `add new entry button` is hidden. 
Once a new entry has been submitted, new button is visible again.

I am also wondering, where the entries are being displayed. 

For the moment, users are able to enter new entries but they are not shown anywhere. This is not the best user experience.

Before adding the form to add new entries, I would decide on a place where the entries are being shown and maybe start out with some dummy data as placeholders.

I would order the user stories like this:
- US 2: journal entries are being displayed (can be static data)
- US 3: form page is implemented and new entries are added to the existing entries

Apart from that, the user story is really nice, but it is missing that one dependency.

I hope this helps :)

**Comment by NikRoe** [comment]
Hi Iris,

you should split this user story into two parts - that did not become completely clear from my previous comment, my bad.

The list entry page should be one user story: You should specify what exactly will be displayed and maybe think about if there is a back button to navigate back. 

The form page should be another user story: Will your form be a component? If so, please specify. Will there be some sort of form validation? (e.g. are any fields required) If so, please specify this is your user story.

When working on your user stories you should implement the entry page first and the add form later.

**Comment by RobinWitt** [comment]
Updated User Story looks good to me, although I would say the complexity is L, because you have to add a second Page, add a db, import/fetch the data and map it into your page.

**Comment by IrisHerholz** [comment]
Hey Robin, thx for the reviews!

I meant with static data, data with a format like
[{ "title": "Entry 1"},
{ "title": "Entry 2"},
{ "title": "Entry 3"}];
to create a place where my entries are shown (there just placeholder entries)

i thought this is what Niklas meant with "static data"...

**Comment by RobinWitt** [comment]
Okay, I didn't read that correctly. Should be fine then.

**Comment by Long-HaHoang** [comment]
It's better if you use check boxes in your acceptance criteria and tasks.
There is benefit to it.
If there are check boxes open tasks will be shown next to your issue.
