### ISSUE TITLE
Userstory 3: Add navigation bar

### ISSUE THREAD

**Issue by IrisHerholz** [IrisHerholz/capstone-project#3]
## Value Proposition

**As a** user  
**I want to** be able to switch between all  pages
**so that** I can navigate the app more easily.

## Description

![Bildschirmfoto 2023-01-28 um 23 22 16](https://user-images.githubusercontent.com/118169582/215293773-dc855098-76a4-4c55-8604-9f353f182003.png)

## Acceptance Criteria

- The user should have a way to switch between the home page and the journal entry page 
- The navigation bar contains a 'home' link field and a 'entry list' link field
- The link fields are highlighted if the user is on the corresponding page
- The user should be able to switch back and forth between all pages 

## Tasks

- Create the component Navigation
- Create a navigation bar with two link fields which are all linked to the respective page
- The link fields are highlighted when you click one and stays highlighted until you click on another one

## Complexity

S

**Comment by NikRoe** [comment]
Hey Iris,

very nice user story!

In your acceptance criteria I would specify where each link actually leads. Something similar to this:
- clicking the home icon leads to the home page
- clicking the add icon leads to the form page

In your wireframes it appears that the icons are highlighted if the user is on the corresponding page. If you intend to work with a logic that handles this for you, you should mention the logic in your tasks and point the highlighting out in your acceptance criteria. If you intend to work with an icon for highlighted / un-highlighted pages, you should also mention this to be clear about your approach.

There is one point that is not yet clear to me: What do you mean by "clear labelling"? Can you be more specific about this?

Cheers

**Comment by IrisHerholz** [comment]
Hy Niklas,
I meant  by "clear labelling" what you mentioned in the first point with "clicking ...". So I'll rewrite it.

I want the icons to be highlighted / un-highlighted and will add that as well. 

Thanks for the feedback!

**Comment by marcterre** [comment]
Hello Iris,
love your app idea!
Your highlighting is a little bit irritating. In your first wireframe it looks like you are on the home page. Maybe use some color for the next time?
Have Fun

**Comment by IrisHerholz** [comment]
Hey Marc,
thats really nice to hear :)) 

And i think about colored highlighting, good hint! Thx!

**Comment by AstridOttmann** [comment]
Hey Iris, it works like it is supposed to do.
Just one note: 
it would be nice when the input is cleared after submitting( event.target.reset();)

**Comment by IrisHerholz** [comment]
Yes, this is on my to do list :P but thx, i will fix it :)
