### ISSUE TITLE
Userstory 4: Form Page

### ISSUE THREAD

**Issue by IrisHerholz** [IrisHerholz/capstone-project#4]
## Value Proposition

**As a** User
**I want to** I want to be able to do a journal entry and save it 
**so that** I remember the special moments of my journey. 

## Description

![Bildschirmfoto 2023-01-29 um 17 27 40](https://user-images.githubusercontent.com/118169582/215340163-c468ab96-2b44-44ae-b2c9-2fbd352dfc8c.png)

## Acceptance Criteria

- The form page is implemented
- The title is positioned fixed on top of the screen
- The input fields for the journal entry are displayed 
- All inputs are required
- The input fields have a appropriate validation
- A save button is displayed in the end of the form
- The entry is saved after clicking the save button and navigates to entry list page 
- The entry is saved in the entry list on the entry list page where all entries are listed
- A button with a link to the form page is displayed on the landing page 

## Tasks

- create a 'Form' component with a index.js 
- create a input field with a placeholder
- create a form for the journal entry with four input fields 
  (start date, end date, title of the journal entry, journal entry)
- create a button for save the entry on the entry list page
-  write a function for the save-case 
- create an add a link to the form page on in navbar 

## Complexity

M

**Comment by RobinWitt** [comment]
This User Story is very descriptive and clear. One thing I would change is not to use any images or image placeholders for the moment, since you are not planning to implement a picture-uploading function for now.
